mcreboot.sh: Fix option error handling
Change-Id: I3af99d7a117d4401c2e0a143fa74513094a53302

diff --git a/arch/x86_64/tools/mcreboot-smp-x86.sh.in b/arch/x86_64/tools/mcreboot-smp-x86.sh.in
--- a/arch/x86_64/tools/mcreboot-smp-x86.sh.in
+++ b/arch/x86_64/tools/mcreboot-smp-x86.sh.in
@@ -78,7 +78,9 @@ do
 		;;
 	O) allow_oversubscribe="allow_oversubscribe"
 		;;
-	*)  echo "invalid option -${OPT}" >&2
+	\?)  echo "Invalid option: -${OPTARG}" >&2
+		exit 1
+	:)  echo "Option -${OPTARG} requires an argument" >&2
 		exit 1
 	esac
 done
