mcstop+release: use ihkconfig release mem all

diff --git a/arch/x86_64/tools/mcstop+release-smp-x86.sh.in b/arch/x86_64/tools/mcstop+release-smp-x86.sh.in
--- a/arch/x86_64/tools/mcstop+release-smp-x86.sh.in
+++ b/arch/x86_64/tools/mcstop+release-smp-x86.sh.in
@@ -62,17 +62,23 @@ if [ "${cpus}" != "" ]; then
 	fi
 fi
 
-if ! ${SBINDIR}/ihkconfig 0 query mem > /dev/null; then
-	echo "error: querying memory" >&2
-	exit 1
-fi
+#if ! ${SBINDIR}/ihkconfig 0 query mem > /dev/null; then
+#	echo "error: querying memory" >&2
+#	exit 1
+#fi
+#
+#mem=`${SBINDIR}/ihkconfig 0 query mem`
+#if [ "${mem}" != "" ]; then
+#	if ! ${SBINDIR}/ihkconfig 0 release mem $mem > /dev/null; then
+#		echo "error: releasing memory" >&2
+#		exit 1
+#	fi
+#fi
 
-mem=`${SBINDIR}/ihkconfig 0 query mem`
-if [ "${mem}" != "" ]; then
-	if ! ${SBINDIR}/ihkconfig 0 release mem $mem > /dev/null; then
-		echo "error: releasing memory" >&2
-		exit 1
-	fi
+# Release all memory
+if ! ${SBINDIR}/ihkconfig 0 release mem "all" > /dev/null; then
+	echo "error: releasing memory" >&2
+	exit 1
 fi
 
 # Remove delegator if loaded
