mcstop+release.sh: Continue when releasing CPUs failed
Change-Id: Ib947843006ae9caa602e7b55309e68365edf4b2a

diff --git a/scripts/mcstop+release-smp.sh.in b/scripts/mcstop+release-smp.sh.in
--- a/scripts/mcstop+release-smp.sh.in
+++ b/scripts/mcstop+release-smp.sh.in
@@ -92,8 +92,7 @@ fi
 cpus=`sudo ${SBINDIR}/ihkconfig 0 query cpu`
 if [ "${cpus}" != "" ]; then
 	if ! sudo ${SBINDIR}/ihkconfig 0 release cpu $cpus > /dev/null; then
-		echo "error: releasing CPUs" >&2
-		exit 1
+		echo "warning: failed to release CPUs" >&2
 	fi
 fi
 
