POSTK_DEBUG_ARCH_DEP_95 fix for mcstop+release.sh

diff --git a/arch/x86/tools/mcoverlay-destroy-smp-x86.sh.in b/arch/x86/tools/mcoverlay-destroy-smp-x86.sh.in
--- a/arch/x86/tools/mcoverlay-destroy-smp-x86.sh.in
+++ b/arch/x86/tools/mcoverlay-destroy-smp-x86.sh.in
@@ -2,19 +2,17 @@
 
 # POSTK_DEBUG_ARCH_DEP_95 if disable mcoverlayfs script nothing to do
 ENABLE_MCOVERLAYFS="@ENABLE_MCOVERLAYFS@"
-if [ "${ENABLE_MCOVERLAYFS}" != "yes" ]; then
-	exit 0
-fi
-# POSTK_DEBUG_ARCH_DEP_95 end
-
-if grep mcoverlay /proc/modules &>/dev/null; then
-    if [ "`cat /proc/mounts | grep /tmp/mcos/mcos0_sys`" != "" ]; then umount -l /tmp/mcos/mcos0_sys; fi
-    if [ "`cat /proc/mounts | grep /tmp/mcos/mcos0_proc`" != "" ]; then umount -l /tmp/mcos/mcos0_proc; fi
-    if [ "`cat /proc/mounts | grep /tmp/mcos/linux_proc`" != "" ]; then umount -l /tmp/mcos/linux_proc; fi
-    if [ "`cat /proc/mounts | grep /tmp/mcos`" != "" ]; then umount -l /tmp/mcos; fi
-    if [ -e /tmp/mcos ]; then rm -rf /tmp/mcos; fi
-    if ! rmmod mcoverlay 2>/dev/null; then
-	echo "error: removing mcoverlay" >&2
-	exit 1
+if [ "${ENABLE_MCOVERLAYFS}" == "yes" ]; then
+    if grep mcoverlay /proc/modules &>/dev/null; then
+        if [ "`cat /proc/mounts | grep /tmp/mcos/mcos0_sys`" != "" ]; then umount -l /tmp/mcos/mcos0_sys; fi
+        if [ "`cat /proc/mounts | grep /tmp/mcos/mcos0_proc`" != "" ]; then umount -l /tmp/mcos/mcos0_proc; fi
+        if [ "`cat /proc/mounts | grep /tmp/mcos/linux_proc`" != "" ]; then umount -l /tmp/mcos/linux_proc; fi
+        if [ "`cat /proc/mounts | grep /tmp/mcos`" != "" ]; then umount -l /tmp/mcos; fi
+        if [ -e /tmp/mcos ]; then rm -rf /tmp/mcos; fi
+        if ! rmmod mcoverlay 2>/dev/null; then
+            echo "error: removing mcoverlay" >&2
+            exit 1
+        fi
     fi
 fi
+# POSTK_DEBUG_ARCH_DEP_95 end
