Change x86 to @ARCH@ in mcreboot-smp-x86.sh.in
since it is used for smp-x86 and smp-arm64

diff --git a/arch/x86/tools/mcreboot-smp-x86.sh.in b/arch/x86/tools/mcreboot-smp-x86.sh.in
--- a/arch/x86/tools/mcreboot-smp-x86.sh.in
+++ b/arch/x86/tools/mcreboot-smp-x86.sh.in
@@ -152,7 +152,7 @@ error_exit() {
 		fi
 		;&
 	ihk_smp_loaded)
-		rmmod ihk_smp_x86 2>/dev/null || echo "warning: failed to remove ihk_smp_x86" >&2
+		rmmod ihk_smp_@ARCH@ 2>/dev/null || echo "warning: failed to remove ihk_smp_@ARCH@" >&2
 		;&
 	ihk_loaded)
 		rmmod ihk 2>/dev/null || echo "warning: failed to remove ihk" >&2
@@ -281,7 +281,7 @@ echo 1 > /proc/sys/vm/compact_memory 2>/dev/null
 sync
 
 # Load IHK-SMP if not loaded and reserve CPUs and memory
-if ! grep ihk_smp_x86 /proc/modules &>/dev/null; then
+if ! grep ihk_smp_@ARCH@ /proc/modules &>/dev/null; then
 	if [ "$ihk_irq" == "" ]; then
 		for i in `seq 64 255`; do
 			if [ ! -d /proc/irq/$i ] && [ "`cat /proc/interrupts | grep ":" | awk '{print $1}' | grep -o '[0-9]*' | grep -e '^$i$'`" == "" ]; then
@@ -294,8 +294,8 @@ if ! grep ihk_smp_x86 /proc/modules &>/dev/null; then
 			error_exit "ihk_loaded"
 		fi
 	fi
-	if ! taskset -c 0 insmod ${KMODDIR}/ihk-smp-x86.ko ihk_start_irq=$ihk_irq ihk_ikc_irq_core=$ihk_ikc_irq_core 2>/dev/null; then
-		echo "error: loading ihk-smp-x86" >&2
+	if ! taskset -c 0 insmod ${KMODDIR}/ihk-smp-@ARCH@.ko ihk_start_irq=$ihk_irq ihk_ikc_irq_core=$ihk_ikc_irq_core 2>/dev/null; then
+		echo "error: loading ihk-smp-@ARCH@" >&2
 		error_exit "ihk_loaded"
 	fi
 
